jobs:
# - name: agg_sf_opps_6hrs
#   targetName: dev
#   schedule: 0 */6 * * *
#   timeout: 25m
#   steps:
#     - name: run models
#       command: dbt run --select agg_salesforce__opportunities
#     - name: build docs
#       command: dbt docs generate
