version: 2

sources:
  - name: hrncir_sf
    database: davidhrncir_demo
    schema: hrncir_01242023_sfdc
    tables:
      - name: opportunity
    tags:
      - h_sfdc

#models:
#  - name: agg_salesforce__opportunities
#    columns:
#      - name: stage_average
#        tests:
#          - not_null